FABReport/Controllers/EmailSettings/EmailSettingsController.cs
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using KABReport.Models;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using System.Web.Routing;
using System.Data.Entity;
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using KABReport.Schedule;
using Quartz;
using Fruitful.Email;
using System.Net.Mail;

namespace KABReport.Controllers
{
    [Authorize(Roles = "Admin, Super Admin")]
    public class EmailSettingsController : BaseController
    {
        [HttpGet]
        public ActionResult Edit()
        {
            using (var context = new SnapDbContext())
            {
                var model = context.EmailSettings.First();
                return View(model);
            }
        }

        [HttpPost]
        public ActionResult Edit(Fruitful.Email.EmailSetting emailSetting)
        {
            using (var context = new SnapDbContext())
            {
                var model = context.EmailSettings.First();
                if (ModelState.IsValid)
                {
                    if (emailSetting.Threshhold / emailSetting.Interval >= 7)
                    {
                        ViewBag.ErrorMessage = "The batch conditions that you have entered are unsuitable. Please select a batch configuration that does not exceed the ratio of 7 emails sent every 1 second.";
                        return View(model);
                    }

                    Schedule.Schedule.ChangeEmailBatchingInterval(model.Interval, emailSetting.Interval);
                    Schedule.ScheduleSendingEmail.ThreshHold = emailSetting.Threshhold;

                    model.Email = emailSetting.Email;
                    model.EnableSSL = emailSetting.EnableSSL;
                    model.Host = emailSetting.Host;
                    model.Password = emailSetting.Password;
                    model.Port = emailSetting.Port;
                    model.Threshhold = emailSetting.Threshhold;
                    model.Interval = emailSetting.Interval;
                    context.SaveChanges();



                    ViewBag.Saved = "Success";
                }
                return View(model);
            }
        }

        [HttpPost]
        public ActionResult SendTestMail(string emailFrom, string password, string host, int port, bool enableSSL, string emailTo)
        {
            EmailSetting emailSetting = new EmailSetting()
            {
                Email = emailFrom,
                Password = password,
                Host = host,
                Port = port,
                EnableSSL = enableSSL
            };

            Emailer emailer = new Emailer(emailSetting);

            MailMessage mailMessage = new MailMessage()
            {
                Subject = "K&B Email setting test",
                IsBodyHtml = true,
                Body = "Success",
            };
            mailMessage.To.Add(emailTo);
            try
            {
                string error;
                emailer.SendEmail(mailMessage, out error);
            }
            catch
            {
                return Json(new { Status = "Fail", Message = "Oops! Something wrong with your email settings." });
            }

            return Json(new { Status = "Success", Message = "Sent. Please check the mailbox to make sure the settings is correct." });
        }
    }

}

FABReport/Views/EmailSettings/Edit.cshtml
@model Fruitful.Email.EmailSetting
@{
    ViewBag.Title = "Edit Email Settings";
}

<div id="divEdit" class="container">
    <div class="row">
        <div class="col-sm-12">
            @if (ViewBag.SuccessMessage != null)
            {
                <div class="alert alert-success">
                    @ViewBag.SuccessMessage
                </div>
            }
            @if (ViewBag.ErrorMessage != null)
            {
                <div class="alert alert-danger">
                    <strong>Error:</strong> @ViewBag.ErrorMessage
                </div>
            }
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <h2>@ViewBag.Title</h2>
        </div>
        <div class="col-sm-6">
            <br />
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <hr />
            @using (Html.BeginForm("Edit", "EmailSettings", FormMethod.Post))
            {  
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.ID)

                    <div class="row" style="margin:0px; padding:0px;">
                        <div class="col-sm-12"></div>
                        <div class="col-sm-4">
                            @Html.LabelFor(model => model.Email)
                            @Html.TextBoxFor(model => model.Email, new { @class = "form-control input-sm" })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                            <br />

                            @Html.LabelFor(model => model.Password)
                            @Html.TextBoxFor(model => model.Password, new { @class = "form-control input-sm", @type="password" })
                            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                            <br />

                            @Html.LabelFor(model => model.Host)
                            @Html.TextBoxFor(model => model.Host, new { @class = "form-control input-sm" })
                            @Html.ValidationMessageFor(model => model.Host, "", new { @class = "text-danger" })
                            <br />

                            @Html.LabelFor(model => model.Port)
                            @Html.TextBoxFor(model => model.Port, new { @class = "form-control input-sm", @type = "number" })
                            @Html.ValidationMessageFor(model => model.Port, "", new { @class = "text-danger" })
                            <br />

                            @Html.LabelFor(model => model.Interval)
                            @Html.TextBoxFor(model => model.Interval, new { @class = "form-control input-sm", @type = "number" })
                            @Html.ValidationMessageFor(model => model.Interval, "", new { @class = "text-danger" })
                            <br />

                            @Html.LabelFor(model => model.Threshhold)
                            @Html.TextBoxFor(model => model.Threshhold, new { @class = "form-control input-sm", @type = "number" })
                            @Html.ValidationMessageFor(model => model.Threshhold, "", new { @class = "text-danger" })
                            <br />

                            @Html.LabelFor(model => model.EnableSSL)
                            @Html.CheckBoxFor(model => model.EnableSSL)
                            @Html.ValidationMessageFor(model => model.EnableSSL, "", new { @class = "text-danger" })
                            <br />

                        </div>
                        <div class="col-sm-12">
                            <hr />
                            @*<a class="btn btn-sm btn-inverse" data-toggle="modal" data-target="#myModal"><span class="fa fa-info"></span>&nbsp; Send a Testing Mail</a>*@
                            <input type="submit" value="Save Changes" class="btn btn-success" />
                            @if (ViewBag.Saved != null)
                            {
                                <label id="l_Saved"><strong>Details Saved!</strong></label>
                                <script>
                                    setTimeout(function () { $("#l_Saved").css("display", "none"); }, 2000);
                                </script>
                            }
                        </div>
                    </div>
            }
            </div>
        </div>
    </div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document" style="width:400px;">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-center">Send a Testing Mail</h5>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-sm-12">
                        <label>Send To: </label>
                        @Html.TextBox("emailTo", "", new { @style = "width:100%;", @id = "emailTo" })
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <a class="btn btn-sm btn-primary" onclick="SendTest()"><span class="glyphicon glyphicon-send "></span>&nbsp; Send</a>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<script>
    function SendTest() {
        $.ajax({
            url: '/EmailSettings/SendTestMail',
            type: 'POST',
            data: {
                emailFrom: $('#Email').val(),
                password: $('#Password').val(),
                host: $('#Host').val(),
                port: $('#Port').val(),
                enableSSL: $('#EnableSSL').val(),
                emailTo: $('#emailTo').val()
            },
            success: function (response) {
                alert(response.Message);
                $('#myModal').modal('hide');
            }
        })
    }
</script>