FABReport/Controllers/Languages/LanguageSetsController.cs
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using KABReport.Models;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;
using System.Web.Routing;
using System.Data.Entity;
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using Fruitful.Import;
using System.Data;

namespace KABReport.Controllers
{
    [Authorize(Roles = "Admin, Super Admin")]
    public class LanguageSetsController : GridController<LanguageSet, LanguageSetViewModel>
    {

        public LanguageSetsController()
            : base(new LanguageSetRepository(), new LanguageSetMapper())
        {

        }


        // GET: LanguageSets
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View(new LanguageSetViewModel());             
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddLanguageSet([DataSourceRequest] DataSourceRequest request, LanguageSetViewModel viewModel)
        {
            LanguageRepository languageRepo = new LanguageRepository();
            Language language = languageRepo.Read().Where(l => l.Name == viewModel.Language.Name && l.Label == viewModel.Language.Label).FirstOrDefault();
            
            if (language != null)
            {
                ViewBag.ErrorMessage = "Language already exists";
                return View(viewModel);
            }

            Language newLanguage = new Language()
            {
                Label = viewModel.Language.Label,
                Name = viewModel.Language.Name
            };
            languageRepo.Create(newLanguage);

            viewModel.Language.ID = newLanguage.ID;
            
            LanguageSet model = new LanguageSet();
            _mapper.MapToModel(viewModel, model);
            _repo.Create(model);

            return RedirectToAction("Index");
        }

        // GET: /Edit LanguageSet
        public ActionResult Edit(int ID)
        {
            try
            {
                LanguageSet ls = _repo.Read().Where(o => o.ID == ID).FirstOrDefault();
                LanguageSetViewModel model = _mapper.MapToViewModel(ls);
                return View(model);
            }
            catch
            {
                return View(new LanguageSetViewModel());
            }

        }


        // POST: /Edit LanguageSet
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(LanguageSetViewModel viewModel)
        {
            if (viewModel == null) return RedirectToAction("Index");

            var model = _repo.Find(viewModel.ID);

            //Check to see if model is valid
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }

            _mapper.MapToModel(viewModel, model);
            _repo.Update(model);

            model = _repo.Find(viewModel.ID);
            _mapper.MapToViewModel(model, viewModel);

            ViewBag.Saved = true; //Return a viewbag variable. Used to show message in front-end html.
            return View(viewModel);

        }

        [HttpPost]
        public override JsonResult Destroy([DataSourceRequest] DataSourceRequest request, LanguageSetViewModel viewModel)
        {
            // Delete language set
            var model = new LanguageSet { ID = viewModel.ID };
            _repo.Delete(model);

            // Delete email template
            var emailTemplateRepo = new ProjectEmailTemplateRepository();
            var emailTemplateList = emailTemplateRepo.Read().Where(et => et.LanguageID == viewModel.ID);
            emailTemplateRepo.Delete(emailTemplateList);

            // Delete Guidance
            var guidanceRepo = new ProjectGuidanceRepository();
            var guidancelist = guidanceRepo.Read().Where(pg => pg.LanguageID == viewModel.ID);
            guidanceRepo.Delete(guidancelist);

            // Delete Language
            var languageModel = new Language(){ ID = viewModel.Language.ID};
            new LanguageRepository().Delete(languageModel);

            return Json(new[] { viewModel }.ToDataSourceResult(request, ModelState));
        }

        // GET: LanguageImport
        public ActionResult Import()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Import(HttpPostedFileBase file)
        {
            const string relativePath = "/Imports/";

            const string column_LanguageName = "Language Name";
            const string column_LanguageLabel = "Language Label";
            const string column_Label_Reports = "Label (Reports)";
            const string column_Label_Refresh = "Label (Refresh)";
            const string column_Label_SearchPlaceholder = "Label (Search Placeholder)";
            const string column_Label_ReportName = "Label (Report Name)";
            const string column_Label_Type = "Label (Type)";
            const string column_Label_Uploaded = "Label (Uploaded)";
            const string column_Label_Hello = "Label (Hello)";
            const string column_Label_LogOff = "Label (Log Off)";
            const string column_Label_NotYet = "Label (Not Yet)";
            const string column_Label_NoReportsFound = "Label (No Reports Found)";

            if (file == null)
            {
                ViewBag.ErrorMessage = "No file has been uploaded.";
                return View();
            }

            string extension = Path.GetExtension(file.FileName);
            if (extension != ".xls" && extension != ".xlsx")
            {
                ViewBag.ErrorMessage = "Uploaded file is the wrong file format.";
                return View();
            }

            var physicalSavePath = SaveFile(file, relativePath);

            var data = ImportService.CopyExcelFileToTable(physicalSavePath, true);

            string error = "";
            string[] columns = new string[] { column_LanguageName, column_LanguageLabel, column_Label_Reports, column_Label_Refresh, column_Label_SearchPlaceholder, column_Label_ReportName, column_Label_Type, column_Label_Uploaded, column_Label_Hello, column_Label_LogOff, column_Label_NotYet, column_Label_NoReportsFound };

            if (!ImportService.IsTableValid(data, columns, out error))
            {
                ViewBag.ErrorMessage = error;
                return View();
            }

            var languageRepo = new LanguageRepository();
            var newLanguageSetList = new List<LanguageSet>();
            foreach (DataRow row in data.Rows)
            {
                if (string.IsNullOrWhiteSpace(row[column_LanguageName].ToString())) continue;

                string languageName = row[column_LanguageName].ToString();
                string languageLabel = row[column_LanguageLabel].ToString();
                string label_Reports = row[column_Label_Reports].ToString();
                string label_Refresh = row[column_Label_Refresh].ToString();
                string label_SearchPlaceholder = row[column_Label_SearchPlaceholder].ToString();
                string label_ReportName = row[column_Label_ReportName].ToString();
                string label_Type = row[column_Label_Type].ToString();
                string label_Uploade = row[column_Label_Uploaded].ToString();
                string label_Hello = row[column_Label_Hello].ToString();
                string label_LogOff = row[column_Label_LogOff].ToString();
                string label_NotYet = row[column_Label_NotYet].ToString();
                string label_NoReportsFound = row[column_Label_NoReportsFound].ToString();

                // Add new language
                var newLanguage = new Language()
                {
                    Name = languageName,
                    Label = languageLabel
                };
                languageRepo.Create(newLanguage);

                // Add new language set
                var newLanguageSet = new LanguageSet()
                {
                    LanguageID = newLanguage.ID,
                    Label_Hello = label_Hello,
                    Label_LogOff = label_LogOff,
                    Label_NoReportsFound = label_NoReportsFound,
                    Label_NotYet = label_NotYet,
                    Label_Refresh = label_Refresh,
                    Label_ReportName = label_ReportName,
                    Label_Reports = label_Reports,
                    Label_SearchPlaceholder = label_SearchPlaceholder,
                    Label_Type = label_Type,
                    Label_Uploaded = column_Label_Uploaded
                };
                newLanguageSetList.Add(newLanguageSet);
            }

            var languageSetRepo = new LanguageSetRepository();
            languageSetRepo.Create(newLanguageSetList);

            ViewBag.SuccessMessage = string.Format("{0} Language have been successfully imported.", data.Rows.Count);
            return View();
        }

    }
    
}

FABReport/Views/LanguageSets/Create.cshtml
@model KABReport.Models.LanguageSetViewModel
@{
    ViewBag.Title = "Edit User";
}

<div id="divEdit" class="container">
    <div class="row">
        <div class="col-sm-12">
            @if (ViewBag.SuccessMessage != null)
            {
                <div class="alert alert-success">
                    @ViewBag.SuccessMessage
                </div>
            }
            @if (ViewBag.ErrorMessage != null)
            {
                <div class="alert alert-danger">
                    <strong>Error:</strong> @ViewBag.ErrorMessage
                </div>
            }
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <h2>Create Language Set</h2>
        </div>
        <div class="col-sm-6">
            <br />
            <a class="btn btn-default hidden-xs" style="float:right" href="~/LanguageSets/"><span class="glyphicon glyphicon-arrow-left"></span>&nbsp;Back To Language Sets</a>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <hr />
            @using (Html.BeginForm("AddLanguageSet", "LanguageSets", FormMethod.Post))
            {  
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                
                    <div class="row" style="margin:0px; padding:0px;">
                        <div class="col-sm-12"></div>
                        <div class="col-sm-4">
                            <label style="color:red">Language Name</label>
                            @Html.TextBoxFor(model => model.Language.Name, new { @class = "form-control input-sm" })
                            @Html.ValidationMessageFor(model => model.Language.Name, "", new { @class = "text-danger" })
                            <br />
                        </div>
                        <div class="col-sm-4">
                            <label style="color:red">Language Label</label>
                            @Html.TextBoxFor(model => model.Language.Label, new { @class = "form-control input-sm" })
                            @Html.ValidationMessageFor(model => model.Language.Label, "", new { @class = "text-danger" })
                            <br />
                        </div>
                        <div class="col-sm-12"></div>
                        <div class="col-sm-4">
                            <label>Label (Hello)</label>
                            @Html.TextBoxFor(model => model.Label_Hello, new { @class = "form-control input-sm" })
                            @Html.ValidationMessageFor(model => model.Label_Hello, "", new { @class = "text-danger" })
                            <br />

                            <label>Label (Log Off)</label>
                            @Html.TextBoxFor(model => model.Label_LogOff, new { @class = "form-control input-sm" })
                            @Html.ValidationMessageFor(model => model.Label_LogOff, "", new { @class = "text-danger" })
                            <br />

                            <label>Label (No Reports Found)</label><br />
                            @Html.TextBoxFor(model => model.Label_NoReportsFound, new { @class = "form-control input-sm" })
                            @Html.ValidationMessageFor(model => model.Label_NoReportsFound, "", new { @class = "text-danger" })
                            <br />

                            <label>Label (Not Yet)</label>
                            @Html.TextBoxFor(model => model.Label_NotYet, new { @class = "form-control input-sm" })
                            @Html.ValidationMessageFor(model => model.Label_NotYet, "", new { @class = "text-danger" })
                            <br />

                            <label>Label (Type)</label>
                            @Html.TextBoxFor(model => model.Label_Type, new { @class = "form-control input-sm" })
                            @Html.ValidationMessageFor(model => model.Label_Type, "", new { @class = "text-danger" })
                            <br />

                            <label>Label (Download)</label>
                            @Html.TextBoxFor(model => model.Label_Download, new { @class = "form-control input-sm" })
                            @Html.ValidationMessageFor(model => model.Label_Download, "", new { @class = "text-danger" })
                            <br />

                            <label>Label (Download All)</label>
                            @Html.TextBoxFor(model => model.Label_DownloadAll, new { @class = "form-control input-sm" })
                            @Html.ValidationMessageFor(model => model.Label_DownloadAll, "", new { @class = "text-danger" })
                            <br />

                        </div>
                        <div class="col-sm-4">
                            <label>Label (Refresh)</label><br />
                            @Html.TextBoxFor(model => model.Label_Refresh, new { @class = "form-control input-sm" })
                            @Html.ValidationMessageFor(model => model.Label_Refresh, "", new { @class = "text-danger" })
                            <br />

                            <label>Label (Report Name)</label>
                            @Html.TextBoxFor(model => model.Label_ReportName, new { @class = "form-control input-sm" })
                            @Html.ValidationMessageFor(model => model.Label_ReportName, "", new { @class = "text-danger" })
                            <br />

                            <label>Label (Reports)</label><br />
                            @Html.TextBoxFor(model => model.Label_Reports, new { @class = "form-control input-sm" })
                            @Html.ValidationMessageFor(model => model.Label_Reports, "", new { @class = "text-danger" })
                            <br />

                            <label>Label (SearchPlaceholder)</label>
                            @Html.TextBoxFor(model => model.Label_SearchPlaceholder, new { @class = "form-control input-sm" })
                            @Html.ValidationMessageFor(model => model.Label_SearchPlaceholder, "", new { @class = "text-danger" })
                            <br />

                            <label>Label (Uploaded)</label>
                            @Html.TextBoxFor(model => model.Label_Uploaded, new { @class = "form-control input-sm" })
                            @Html.ValidationMessageFor(model => model.Label_Uploaded, "", new { @class = "text-danger" })
                            <br />

                            <label>Label (Select All)</label>
                            @Html.TextBoxFor(model => model.Label_SelectAll, new { @class = "form-control input-sm" })
                            @Html.ValidationMessageFor(model => model.Label_SelectAll, "", new { @class = "text-danger" })
                            <br />
                        </div>
                        <div class="col-sm-12">
                            <hr />
                            <input type="submit" value="Save Changes" class="btn btn-success" />
                        </div>
                    </div>
            }
            </div>
        </div>
    </div>

FABReport/Views/LanguageSets/Edit.cshtml
@model KABReport.Models.LanguageSetViewModel
@{
    ViewBag.Title = "Edit User";
}

<div id="divEdit" class="container">
    <div class="row">
        <div class="col-sm-12">
            @if (ViewBag.SuccessMessage != null)
            {
                <div class="alert alert-success">
                    @ViewBag.SuccessMessage
                </div>
            }
            @if (ViewBag.ErrorMessage != null)
            {
                <div class="alert alert-danger">
                    <strong>Error:</strong> @ViewBag.ErrorMessage
                </div>
            }
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <h2>Edit Language Set</h2>
            <h3 style="color:grey">@Model.Language.Label (@Model.Language.Name)</h3>
        </div>
        <div class="col-sm-6">
            <br />
            <a class="btn btn-default hidden-xs" style="float:right" href="~/LanguageSets/"><span class="glyphicon glyphicon-arrow-left"></span>&nbsp;Back To Language Sets</a>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <hr />
            @using (Html.BeginForm("Edit", "LanguageSets", FormMethod.Post))
            {  
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.ID)
                    @Html.HiddenFor(model => model.Language.ID)
                    @Html.HiddenFor(model => model.Language.Name)
                    @Html.HiddenFor(model => model.Language.Label)
                
                    <div class="row" style="margin:0px; padding:0px;">
                        <div class="col-sm-12"></div>
                        <div class="col-sm-4">
                            <label>Label (Hello)</label>
                            @Html.TextBoxFor(model => model.Label_Hello, new { @class = "form-control input-sm" })
                            @Html.ValidationMessageFor(model => model.Label_Hello, "", new { @class = "text-danger" })
                            <br />

                            <label>Label (Log Off)</label>
                            @Html.TextBoxFor(model => model.Label_LogOff, new { @class = "form-control input-sm" })
                            @Html.ValidationMessageFor(model => model.Label_LogOff, "", new { @class = "text-danger" })
                            <br />

                            <label>Label (No Reports Found)</label><br />
                            @Html.TextBoxFor(model => model.Label_NoReportsFound, new { @class = "form-control input-sm" })
                            @Html.ValidationMessageFor(model => model.Label_NoReportsFound, "", new { @class = "text-danger" })
                            <br />

                            <label>Label (Not Yet)</label>
                            @Html.TextBoxFor(model => model.Label_NotYet, new { @class = "form-control input-sm" })
                            @Html.ValidationMessageFor(model => model.Label_NotYet, "", new { @class = "text-danger" })
                            <br />

                            <label>Label (Type)</label>
                            @Html.TextBoxFor(model => model.Label_Type, new { @class = "form-control input-sm" })
                            @Html.ValidationMessageFor(model => model.Label_Type, "", new { @class = "text-danger" })
                            <br />

                            <label>Label (Download)</label>
                            @Html.TextBoxFor(model => model.Label_Download, new { @class = "form-control input-sm" })
                            @Html.ValidationMessageFor(model => model.Label_Download, "", new { @class = "text-danger" })
                            <br />

                            <label>Label (Download All)</label>
                            @Html.TextBoxFor(model => model.Label_DownloadAll, new { @class = "form-control input-sm" })
                            @Html.ValidationMessageFor(model => model.Label_DownloadAll, "", new { @class = "text-danger" })
                            <br />

                        </div>
                        <div class="col-sm-4">
                            <label>Label (Refresh)</label><br />
                            @Html.TextBoxFor(model => model.Label_Refresh, new { @class = "form-control input-sm" })
                            @Html.ValidationMessageFor(model => model.Label_Refresh, "", new { @class = "text-danger" })
                            <br />

                            <label>Label (Report Name)</label>
                            @Html.TextBoxFor(model => model.Label_ReportName, new { @class = "form-control input-sm" })
                            @Html.ValidationMessageFor(model => model.Label_ReportName, "", new { @class = "text-danger" })
                            <br />

                            <label>Label (Reports)</label><br />
                            @Html.TextBoxFor(model => model.Label_Reports, new { @class = "form-control input-sm" })
                            @Html.ValidationMessageFor(model => model.Label_Reports, "", new { @class = "text-danger" })
                            <br />

                            <label>Label (SearchPlaceholder)</label>
                            @Html.TextBoxFor(model => model.Label_SearchPlaceholder, new { @class = "form-control input-sm" })
                            @Html.ValidationMessageFor(model => model.Label_SearchPlaceholder, "", new { @class = "text-danger" })
                            <br />

                            <label>Label (Uploaded)</label>
                            @Html.TextBoxFor(model => model.Label_Uploaded, new { @class = "form-control input-sm" })
                            @Html.ValidationMessageFor(model => model.Label_Uploaded, "", new { @class = "text-danger" })
                            <br />

                            <label>Label (Select All)</label>
                            @Html.TextBoxFor(model => model.Label_SelectAll, new { @class = "form-control input-sm" })
                            @Html.ValidationMessageFor(model => model.Label_SelectAll, "", new { @class = "text-danger" })
                            <br />
                        </div>
                        <div class="col-sm-12">
                            <hr />
                            <input type="submit" value="Save Changes" class="btn btn-success" />
                            @if (ViewBag.Saved != null)
                            {
                                <label id="l_Saved"><strong>Details Saved!</strong></label>
                                <script>
                                    setTimeout(function () { $("#l_Saved").css("display", "none"); }, 2000);
                                </script>
                            }
                        </div>
                    </div>
            }
            </div>
        </div>
    </div>

FABReport/Views/LanguageSets/Import.cshtml
@{
    ViewBag.Title = "ImportLanguageSet";
}


<div class="container">
    <div class="row">
        <div class="col-sm-12">
            @if (ViewBag.SuccessMessage != null)
            {
                <div class="alert alert-success">
                    @ViewBag.SuccessMessage
                </div>
            }
            @if (ViewBag.ErrorMessage != null)
            {
                <div class="alert alert-danger">
                    <strong>Error:</strong> @ViewBag.ErrorMessage
                </div>
            }
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <h1>Language Import</h1>
            <hr />
        </div>
        <div class="col-sm-12">
            @using (Html.BeginForm("Import", "LanguageSets", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                <div class="col-sm-3">
                    <br />
                    <div class="form-control">
                        <input id="languageFile" type="file" name="file" style="display:inline-block" />
                    </div>
                    <br />
                    <span class="input-group-btn">
                        <input type="submit" value="Import Languages" class="btn btn-primary btn-sm" onclick="return ValidUpload('languageFile');" />
                    </span>
                </div>
            }
        </div>
    </div>
</div>

<style>
    html .k-grid tr:hover {
        background: inherit;
        color: inherit;
    }

    html .k-grid tr.k-alt:hover {
        background: #f5f5f5;
        color: inherit;
    }
</style>

<script>

    function ValidUpload(id) {
        var file = $("#" + id).val();
        if (file == "")
            return false;
        else {
            ShowProgress();
            return true;
        }
    }

</script>

FABReport/Views/LanguageSets/Index.cshtml
@{
    ViewBag.Title = "Language Sets";
}

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            @if (ViewBag.SuccessMessage != null)
            {
                <div class="alert alert-success">
                    @ViewBag.SuccessMessage
                </div>
            }
            @if (ViewBag.ErrorMessage != null)
            {
                <div class="alert alert-danger">
                    <strong>Error:</strong> @ViewBag.ErrorMessage
                </div>
            }
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <h1>Language Sets</h1>
            <hr />
        </div>

        <div class="col-sm-8">
            <a class="btn btn-info" href="@Url.Action("Create")"><span class="glyphicon glyphicon-user"></span> &nbsp;Add New Language Set</a>
        </div>

        @*<div class="col-sm-4">
            <div class="input-group" style="margin-top:5px;">
                @Html.TextBox("TB_UserFilter", null, new { @class = "form-control", @style = "max-width:none", @placeholder = "Search Email/Name" })
                <span class="input-group-btn">
                    <a class="btn btn-sm btn-default" onclick="SearchUsers()"><span class="glyphicon glyphicon-search"></span></a>
                </span>
            </div>
        </div>*@

        <div class="col-sm-12">
            <br />
            @(Html.Kendo().Grid<KABReport.Models.LanguageSetGridViewModel>()
                .Name("GridLanguageSets")
                .Pageable(p => p.PageSizes(new[] { 50, 100, 200 }).Messages(m => m.Display("{0} - {1} of {2} Users").Empty("No Language Sets Found")))
                .Columns(columns =>
                {
                    columns.Bound(ls => ls.ID).Title("ID").Hidden();
                    columns.Bound(u => u.Language.Name).Title("Language Name").ClientTemplate("<strong>#=Language.Name#</strong>");
                    columns.Bound(u => u.Language.Label).Title("Language Label").ClientTemplate("<strong>#=Language.Label#</strong>");
                    columns.Bound(u => u.Label_Hello).Title("Label (Hello)");
                    columns.Bound(u => u.Label_LogOff).Title("Label (Log Off)");
                    columns.Bound(u => u.Label_NotYet).Title("Label (Not Yet)");
                    columns.Bound(u => u.Label_Refresh).Title("Label (Refresh)");
                    columns.Bound(u => u.Label_Reports).Title("Label (Reports)");
                    columns.Bound(u => u.Label_Type).Title("Label (Type)");
                    columns.Template(@<text></text>).ClientTemplate("...");
                    columns.Template(@<text></text>).ClientTemplate("<a href='" + Url.Action("Edit") + "/#=ID#' class='btn btn-xs btn-inverse' >Edit</a>").Width("1%");
                    columns.Command(command =>
                    {
                        command.Destroy().Text("<span class='btn btn-xs btn-danger'>Delete</span>");
                    }
                    ).Width("1%");
                })
                        .Editable(editable => editable.Mode(GridEditMode.InLine).ConfirmDelete("Are you sure you want to delete this language set?"))
                        .DataSource(dataSource => dataSource
                            .Ajax()
                            .Model(model =>
                            {
                                model.Id(t => t.ID);
                                model.Field(t => t.ID).Editable(false);
                            })
                            //Pass the string in the textbox using the anonymously created function
                            .Read(read => read.Action("Read", "LanguageSetGrid").Data("function() { return { filterText: $('#TB_UserFilter').val() }}"))
                            .Destroy(destory => destory.Action("Destroy", "LanguageSets"))
                        )
                        .Events(events => events.DataBound("KendoGridDatabound"))
            )
        </div>
    </div>
</div>

<style>
    html .k-grid tr:hover {
        background: inherit;
        color: inherit;
    }

    html .k-grid tr.k-alt:hover {
        background: #f5f5f5;
        color: inherit;
    }
</style>

<script>
    //$("#TB_UserFilter").keyup(function (e) {
    //    if (e.keyCode == 13) {
    //        SearchUsers();
    //    }
    //});

    function SearchLanguageSets() {
        var grid = $("#GridLanguageSets").data("kendoGrid");
        grid.dataSource.read();
    }
</script>